### ISSUE TITLE
Can you remake it for cmder

### ISSUE THREAD

**Issue by morpheuslord** [Bhaviktutorials/T-Remix#10]
Hello bavik
I seriously loved your tool but I am a windows user and I have a tool for hackers basic level hackers to be precise it's name is brute-hacking-framework and I am working on its new update with a lot more tools and all coming to the point can you please make the same tool for cmder interface please that will be great if you can do that
Thank you
Morpheuslord

**Comment by Bhaviktutorials** [comment]
will surely think about it!!!

**Comment by morpheuslord** [comment]
Thanks a lot
